export const BACKGROUND_MESSAGE_TYPES = {
  GET_NOTION_PAGES: 'GET_NOTION_PAGES',
  IMPORT_TO_NOTION: 'IMPORT_TO_NOTION',
  EXPORT_NOTION_PAGE: 'EXPORT_NOTION_PAGE',
  OPEN_EXTENSION_CONFIG: 'OPEN_EXTENSION_CONFIG',
  CHECK_NOTION_AUTH: 'CHECK_NOTION_AUTH',
};
